Bugfixes in bash functions, startap, and joinParts

diff --git a/bin/startap b/bin/startap
--- a/bin/startap
+++ b/bin/startap
@@ -45,21 +45,29 @@ in $1\e[0m"
 
 ############################ Main ################################
 
+# Create an access pent
 function startap()
 (
+    # Interpret command line options
+    exitAp=0
+    if [[ "$1" == '-x' ]]; then
+        exitAp=1
+        shift
+    fi
+
+    # Get sudo permissions and detect cancel (once normally gives sudo for the next minutes to other calls)
+    if ! sudo true; then exit 1; fi
+
     sudo pkill hostapd
     sudo pkill wpa_supplicant
     if sudo service network-manager status | 'grep' -q 'active (running)'; then
         sudo service isc-dhcp-server stop
     fi
-    sudo nmcli radio wifi off
-
-    if [ "$1" == '-x' ]; then
-        exit 0
-    fi
+    sudo nmcli radio wifi off # Don't let the network manager get in our way of configuring the WiFi
     sleep 0.1
+
     if [[ -f /var/run/dhcpd.pid ]] && ps -p "$( cat /var/run/dhcpd.pid &>/dev/null )"; then
-        echo -e "\e[31mIt seems a rogue dhcpd process is still running with pid $(cat /var/run/dhcpd.pid) (see /var/run/dhcpd.pid)\e[0m"
+        echo -e "\e[31mIt seems a rogue dhcpd process is still running with pid $( cat /var/run/dhcpd.pid ) (see /var/run/dhcpd.pid)\e[0m"
         exit 1
     else
         # See also this bug: https://marc.ttias.be/systemd-devel/2016-06/msg00006.php
@@ -70,11 +78,11 @@ function startap()
     # [    7.402603] ath9k_htc 1-2.1.1:1.0 wlxec086b13468f: renamed from wlan0
     #interface=( $('dmesg' | 'sed' -nE 's/.* ([A-Za-z0-9]*): renamed from wlan[0-9]*/\1/p') )
     interfaces=( $( extractWlans ) )
-    if [ "${#interfaces[@]}" -eq 0 ]; then
+    if [[ "${#interfaces[@]}" -eq 0 ]]; then
         echo "No wlan interface using the new systemd scheme found"
         # Todo: do some other checks, e.g. in ifconfig, iw list, ip link show or old scheme in dmesg, and give hints as to what drivers to install, ...
         exit 1
-    elif [ "${#interfaces[@]}" -eq 1 ]; then
+    elif [[ "${#interfaces[@]}" -eq 1 ]]; then
         interface=$interfaces
     fi
 
@@ -84,6 +92,23 @@ function startap()
             interface=$interf
         fi
     done
+
+    ipAddress='10.0.0.1/24'
+    internetInterface="$( ip route list default | sed -n -r 's|.* dev *([A-Za-z0-9]+).*|\1|p' | head -1 )"
+
+    if [[ "$exitAp" -eq 1 ]]; then
+        # Remove manually set ip address and subnet from device (it won't remove anything if it differs)
+        sudo ip address del "$ipAddress" dev "$interface" &> /dev/null
+
+        # Remove iptable rules created by us even those not explicitly mentioning the specific interface
+        sudo iptables --delete POSTROUTING --table nat --out-interface "$internetInterface" --jump MASQUERADE &>/dev/null
+        sudo iptables --delete FORWARD --table filter --match conntrack --ctstate RELATED,ESTABLISHED --jump ACCEPT &>/dev/null
+        sudo iptables --delete FORWARD --table filter --in-interface "$interface" --out-interface "$internetInterface" --jump ACCEPT &>/dev/null
+
+        exit 0
+    fi
+
+
 
     if [[ "${#interfaces[@]}" -gt 1 && -z $interface ]]; then
         echo -e "Found more than one interface, please choose which to use as an access point: ${interfaces[@]}"
@@ -105,10 +130,8 @@ function startap()
     fi
     echo "Starting hostapd and dhcp-server on interface $interface"
 
-    # echo 1 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
-    export DAEMON_CONF=~/etc/hostapd/hostapd.conf
-    export RUN_DAEMON=yes
-    if [ -d "$1" ]; then
+    # Find home folder for logs and config files
+    if [[ -d "$1" ]]; then
         home=$1
         logs=$1
     else
@@ -116,14 +139,21 @@ function startap()
         logs=$HOME/logs
         mkdir -p -- "$logs"
     fi
-    sudo bash -c "nohup hostapd '$home/etc/hostapd/hostapd.conf' > '$logs/hostapd.log'" &>/dev/null &
+
+    # echo 1 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
+    hostapdConf="$home/etc/hostapd/hostapd.conf"
+    replaceOption "$hostapdConf" 'interface' "$interface"
+    export DAEMON_CONF="$hostapdConf"
+    export RUN_DAEMON=yes
+    sudo bash -c "nohup hostapd '$hostapdConf' >> '$logs/hostapd.log'" &>/dev/null &
 
     replaceOption '/etc/default/isc-dhcp-server' 'DHCPDv4_CONF' "$home/etc/dhcp/dhcpd.conf"
     replaceOption '/etc/default/isc-dhcp-server' 'INTERFACESv4' "\"$interface\""
     replaceOption '/etc/default/isc-dhcp-server' 'INTERFACESv6' '""'
 
-    if ! ip address list dev "$interface" | 'grep' -q '10.0.0.1/24'; then
-        sudo ip address add 10.0.0.1/24 dev "$interface"
+    # ToDo: Find other interface using the same IP and and warn about it and/or remove the IP!
+    if ! ip address show dev "$interface" | 'grep' -q "$ipAddress"; then
+        sudo ip address add "$ipAddress" dev "$interface"
     fi
     sudo service isc-dhcp-server restart
 
@@ -151,7 +181,7 @@ function startap()
             sudo iptables --append "$@"
         fi
     }
-    internetInterface="$( ip route list default | sed -n -r 's|.* dev *([A-Za-z0-9]+).*|\1|p' | head -1 )"
+
     echo "Using interface $internetInterface to route traffic from $interface to the internet."
     addRule POSTROUTING --table nat --out-interface "$internetInterface" --jump MASQUERADE
     addRule FORWARD --table filter --match conntrack --ctstate RELATED,ESTABLISHED --jump ACCEPT
@@ -159,6 +189,11 @@ function startap()
     # sudo iptables --append FORWARD --table filter --in-interface "$interface" --out-interface "$internetInterface" --jump LOG --log-prefix "FORWARD from WLAN to ETH"
 
     # Error checking if access point does not work (not yet automated):
+    #  - Check whether the access point (AP) is up by scanning. This might not work the device the AP is running on. So, check with another device.
+    #    sudo iwlist wlo1 scan | grep SSID
+    #       If it is not up, then something must be wrong with hostapd or the WIFI device?
+    #       - check dmesg for things like iwlwifi. For example, I found multiple "Microcode SW error detected" errors and it seems to hang in a loop trying to restart again and again
+    #       - run hostapd in debug mode with -d
     #  - does the interface used here has an IP address, if not, do: ip address add 10.0.0.1/24 dev $interface
     #  - has the client the correct gateway configured? -> if not, then ping gateway works, but any other IP e.g. ping 8.8.8.8 won't work. Solution: set one manually with ip route or check the DHCP server configuration, whether it has a 'option router 10.0.0.1' at the correct place
     #  - is forwarding working correctly on the gateway? If not, then ping 10.0.0.1 will work but not ping 8.8.8.8
